FROM oven/bun:1.1.20

# hadolint ignore=DL3008
RUN apt-get update \
  && apt-get --no-install-recommends -y install gnupg2 ca-certificates \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists

WORKDIR /workspaces/shikosai33-web/

COPY ./ ./
RUN bun install
