# hadolint ignore=DL3007
FROM ubuntu:latest

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

# hadolint ignore=DL3008
RUN apt-get update \
  && apt-get --no-install-recommends -y install ca-certificates curl git gnupg2 unzip \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists

RUN curl -fsSL https://bun.sh/install | bash

WORKDIR /workspaces/shikosai33-web/

COPY ./ ./
RUN /root/.bun/bin/bun install
